### ISSUE TITLE
Click Wp Sync

### ISSUE THREAD

**Issue by OwnageGalore** [JeanMax/AutoSmurf#1]
autosmurfs sit at wp in town..
the box when pressing home states:
clickWP
sync
start failed
then leaves game and makes a new one.

**Comment by Toft2k** [comment]
I'm having the same issue, and obviously not as bright as Mr. Galore because, I simply can't figure this out.

**Comment by JeanMax** [comment]
It's most likely a configuration issue, try to take another look at the readme, and be sure to use __profile__ name. If it doesn't help, you might want to ask on irc.

**Comment by Toft2k** [comment]
Thanks alot man, it was as you said, a config error.
Anyway thanks for all the work on the autosmurf and the reply, ill buy u a beer some day :)

**Comment by jthack** [comment]
@Toft2k how did you end up figuring it out? mine's doing the same thing.

**Comment by Toft2k** [comment]
Hey man, the barb and sorc are required for it to run. 
I made them sync by only adding the profile names of chars that were in the party, I had just copy pasted from here and left it blank, only ran it with 2. They were probably looking for the other 2 party members, who didnt exist.
Sounds like the Quitlist in your charconfig. If you copy pasted the autosmurf lines from here into your char config, there could be 2 lines with same command.

**Comment by jthack** [comment]
@Toft2k Yeah, i managed to figure it out. Now my bots are doing something funky. When teleporting sorc is trying to start chaos, the boer and other sorc go to catacombs a4 and just stand there..
